version: '3.7'
services:
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html:delegated
  db:
    container_name: ${PROJECT_NAME}_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=${PROJECT_NAME}
      - MYSQL_USER=${PROJECT_NAME}_user
      - MYSQL_PASSWORD=${PROJECT_NAME}_123
    volumes:
    - mysql_data_docker_lamp_laravel:/var/lib/mysql

  phpmyadmin:
    container_name: ${PROJECT_NAME}_pma
    build:
      context: ./pma
      dockerfile: Dockerfile
    environment:
      - UPLOAD_LIMIT=1024M
    depends_on:
      - db
    ports:
      - 8080:80

  maildev:
    container_name: ${PROJECT_NAME}_maildev
    build:
      context: ./maildev
      dockerfile: Dockerfile
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  mysql_data_docker_lamp_laravel: